FROM phusion/baseimage:jammy-1.0.1

WORKDIR '/mnt/'

RUN ["apt","update","-y"]
RUN ["apt","upgrade","-y"]

RUN apt install -y wget default-jdk scala python3 python3-pip 

RUN pip3 install notebook && pip install py4j
RUN pip install sparkmagic
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension
RUN jupyter-kernelspec install --user $(pip show sparkmagic | grep Location | cut -d" " -f2)/sparkmagic/kernels/sparkkernel
RUN jupyter-kernelspec install --user $(pip show sparkmagic | grep Location | cut -d" " -f2)/sparkmagic/kernels/pysparkkernel
RUN jupyter-kernelspec install --user $(pip show sparkmagic | grep Location | cut -d" " -f2)/sparkmagic/kernels/sparkrkernel
RUN jupyter serverextension enable --py sparkmagic

CMD ["start-notebook.sh", "--NotebookApp.iopub_data_rate_limit=1000000000"]